---
title: "API Wrappers"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{api_wrappers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`polished` now comes with functions that make it easy to interact with the Polished API from
R.  See the individual wrapper function help files for details (e.g. `?polished::get_apps()`). 
The available API wrapper functions include:

Apps - functions to manage your account's Shiny apps.  

 - get_apps()
 - add_app()
 - update_app()
 - delete_app()
 
Users  - functions to manage your account's users.

 - get_users()
 - add_user()
 - update_user()
 - delete_user()
 
App Users  - functions to manage user access to your Shiny apps.  These will be the most frequently used
of the API wrapper functions.

- get_app_users()
- add_app_user()
- update_app_user()
- delete_app_user()

Roles - functions to manage your account's roles.

- get_roles()
- add_role()
- delete_role()

User Roles - functions to manage the roles your users belong to.

- get_user_roles()
- add_user_role()
- delete_user_role()
